version: "3"
 
services:
  php:
    build:
      context: ./php
    image: "samelement/sam-web:php"
    hostname: "${COMPOSE_PROJECT_NAME}-php"
    volumes:
      - ..:/app:cached
      - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf:cached
    working_dir: /app
  nginx:
    build:
      context: ./nginx
    image: "samelement/sam-web:nginx"
    hostname: "${COMPOSE_PROJECT_NAME}-nginx"
    ports:
      - "80:80"
    volumes:
      - ..:/app:cached
      - ./nginx/app.conf:/etc/nginx/conf.d/default.conf:cached
    depends_on:
      - php
